<a href="https://colab.research.google.com/github/LucioFassarella/AlgebraLinear/blob/main/AlgebraLinear_Escalonamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Álgebra Linear

## Escalonamento

In [ ]:
import numpy as np

def Escalonamento(matriz : 'list'):

    '''
    Métodos requeridos:
        - numpy as np
    '''

    num_linhas = len(matriz)
    num_cols = len(matriz[0])
    for linha in matriz:
        if len(linha) != num_cols:
            return False

    index_pivos = [num_cols for l in range(num_linhas)]
    for l in range(num_linhas):
        for k in range(num_cols):
            if matriz[l][k] != 0:
                index_pivos[l] = k
                break

    # Teste de matriz nula:
    min_index_pivo = min(index_pivos)
    index_linha_lider = index_pivos.index(min_index_pivo)
    if min_index_pivo == num_cols:
        return matriz

    else: # Troca da linha superior pela linha com pivô mais à esquerda:

        matriza = matriz.copy()

        matriza[0] = matriz[index_linha_lider].copy()
        matriza[index_linha_lider] = matriz[0].copy()

        escada = np.array(matriza).astype(float)

        pivo_lider = escada[0][min_index_pivo]
        escada[0] = escada[0]/pivo_lider


        # Teste de matriz com uma única linha:
        if len(escada) == 1:
            return escada

        else: # Anulação na coluna do pivô da linha superior das entradas inferiores:
            for i in range(1, len(escada)):
                multiplicador = escada[i][min_index_pivo]
                escada[i] = escada[i] - multiplicador * escada[0]

            # Recurssão:
            sub_matriz =  escada[1:]
            if len(sub_matriz) > 0:
              sub_escada = Escalonamento(sub_matriz)
              for l in range(1,num_linhas):
                escada[l] = sub_escada[l - 1]

            escalonada = AnulaCol(escada) # Anulação de coluna diferentes exceto pivô

            return escalonada


def AnulaCol(matriz : 'list'):

    matriza = np.array(matriz).astype(float)

    num_linhas = len(matriza)
    num_cols = len(matriza[0])
    for linha in matriza:
        if len(linha) != num_cols:
            return False

    for l in range(num_linhas):
        for k in range(num_cols):
            if matriza[l][k] != 0:
                for i in range(num_linhas):
                    if i != l:
                        multiplicador = matriza[i][k]/matriza[l][k]
                        matriza[i] = matriza[i] - multiplicador * matriza[l]
                break

    return matriza

In [ ]:
#TESTE

matriz = [
    [0,1,2,3],
[4,5,6,7],
[8,9,10,11]
]
print(f"Matriz:")
print(np.array(matriz))

M = Escalonamento(matriz)

print(f"Matriz escalonada:")
print(M)



Matriz:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Matriz escalonada:
[[ 1.  0. -1. -2.]
 [ 0.  1.  2.  3.]
 [ 0.  0.  0.  0.]]
